### PR TITLE
First Pull Request 

### PR DESCRIPTION
**Pull request by Ismailco**
This is the first pull for this project requared by microverse, the branch has thous files: 	
        - index.html
	- style.css
	- README.md
	- lintes files

### CODE REVIEW

**Review by Dipeshtwis — CHANGES_REQUESTED** [review]
Hi @Ismailco , 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: Good use of .gitignore file.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


 ## Required Changes ♻️

- [x] Linter should be set up correctly for this repository.
- [ ] README file should have description about the project even if it's one or two line so that anyone can understand about your project.
- [ ] There should be no commented code in the style.css file.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- I suggest that your pull request be more descriptive describing introduced changes in more details this is a recommended best practice as it makes reviewing easier.

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**_Dipesh Kumar_**


------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by Ismailco — COMMENTED** [review]
Hi, is this is good, am I doing this right?
if not please give some advice.
how to add the lines? and should I create a new pull request?

**Comment by mricanho** [comment]
> Hi, is this is good, am I doing this right?
> if not please give some advice.
> how to add the lines? and should I create a new pull request?

Hello @Ismailco,

Your WebPage branch has conflicts because you erase the files on the main branch, for future references you don't need to re-start a projector or a Pull Request to make changes, just work on the present branch and fix the requests.

**Review by mricanho — APPROVED** [review]
# Status: ✔️ Project Approved ✔️ 

Hello @Ismailco!

I'm gonna approve this PR because you work on all the instructions that the previous Code Reviewer gives you👍🏽 

**Check the response I made in your comment**

shine team


Now you can merge this branch 🚀 

### 💻 👩🏽‍💻  Happy Coding!  👨🏽‍💻 🖥️

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
